### ISSUE TITLE
errors generated when the data isn't there need to be handled more gracefully

### ISSUE THREAD

**Issue by golemheavy** [golemheavy/liri-node-app#23]
Attempting MOVIE-THIS
Getting IMDB data for movie: Avengers:+Civil+War
        Movie Title:            Kung Fu Avengers: Civil War
        Year Released:          2015
        IMDB Rating:            N/A
TypeError: Cannot read property 'Value' of undefined
    at C:\Users\Steve\Documents\coding\GitHub\liri-node-app\liri.js:150:67
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error:
TypeError: msgTextStr.split is not a function
    at logmsg (C:\Users\Steve\Documents\coding\GitHub\liri-node-app\liri.js:15:14)
    at C:\Users\Steve\Documents\coding\GitHub\liri-node-app\liri.js:157:3
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by golemheavy** [comment]
![missingDataCausesErrors](https://user-images.githubusercontent.com/46508146/57114382-964b5580-6d0e-11e9-8e49-80042cb264d5.PNG)

**Comment by golemheavy** [comment]
I resolved this issue with a try / catch block, but only for the case where Rotten tomatoes data is missing. So something else could happen if the data model is missing things. Especially in the case of arrays, this should be checked.

**Comment by golemheavy** [comment]
![missingDataissueResolved](https://user-images.githubusercontent.com/46508146/57115306-d6610700-6d13-11e9-9031-7715017f8e23.PNG)
